export enum QuestionType {
    SINGLE_LINE_TEXT = "SINGLE_LINE_TEXT",
    MULTILINE_TEXT = "MULTILINE_TEXT",
    RADIO_BUTTON = "RADIO_BUTTON",
    CHECKBOX = "CHECKBOX",
    COMBOBOX = "COMBOBOX",
    DATE = "DATE"
}